# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2806a2a4569e9c3b4ea6f810659f6986ceccf36cfa391d6312b4d09c6237ec5bac2b26338f74c983905ecfb3dc5bec30fa85c71e00c8233203dc16a65e3c2a3d

test:
  secret_key_base: cfbb2d284118259ceb64a4f5fb92716d1328b788f00ead63af7ba0cb6ab0c59b76eebf1cc16b59da6c5cff6c451b8555aa7257f22cd6bae0fb993546ebf30d50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
